# SPDX-License-Identifier: MIT
# Copyright (c) 2021 Chua Hou
#
# Container that will run all our printer/scanner drivers, since that's sadly a
# weak point of NixOS for now.

FROM docker.io/library/debian:stable-slim

# build-args used for configuration
# We have some arguments (e.g. printer URIs) that might make more sense to keep
# as environment variables specific to containers rather than the image, but
# since we want to use them during installation of printer drivers we will do
# use build-args for the image instead. If the network/printer configuration
# changes, a new image should be built.
ARG TZ=Asia/Singapore
ARG BRPRINTER_INST_VERSION=2.2.2-1
ARG BRPRINTER_INST_SHA256=52de70e1f0bfa7aa3af444c7e78a2794d3bfada99f70c0d09e62ec85a549b025
ARG BRPRINTER_IP=192.168.1.1
ARG HPPLUGIN_VERSION=3.18.12
ARG HPPLUGIN_SHA256=84a0dc385083ffc9acd66d3ab9a22a9a0943b9f6ed7db8e406682f6bc7f642a6
ARG HPPRINTER_IP=192.168.1.1

# Expose ports
# 631:  cupsd
# 6566: saned
EXPOSE 631 6566

# Install packages, then clean up
RUN \
	apt-get update \
	&& apt-get install -y \
		ca-certificates curl wget whois cups sane-utils lpr hplip \

	# configure timezone
	&& ln -fs /usr/share/zoneinfo/${TZ} /etc/localtime \
	&& dpkg-reconfigure --frontend noninteractive tzdata \

	# clean cache and package lists
	&& apt-get clean \
	&& rm /var/lib/apt/lists -rf

# Add 'print' user for authentication in CUPS with password 'print'
RUN useradd --groups=sudo,lp,lpadmin --password=$(mkpasswd print) print

# Temporary work will be done here
WORKDIR /work

# Install Brother MFC-J625DW drivers
COPY brprinter-installer.response .
RUN \
	curl https://download.brother.com/welcome/dlf006893/linux-brprinter-installer-${BRPRINTER_INST_VERSION}.gz \
		| gunzip --uncompress > brprinter-installer \
	&& echo "${BRPRINTER_INST_SHA256} brprinter-installer" | sha256sum --check \
	&& chmod +x brprinter-installer \
	&& cat brprinter-installer.response | ./brprinter-installer

# Install HPLIP plugin
RUN \
	wget https://developers.hp.com/sites/default/files/hplip-${HPPLUGIN_VERSION}-plugin.run \
	&& echo "${HPPLUGIN_SHA256} hplip-${HPPLUGIN_VERSION}-plugin.run" | \
		sha256sum --check \
	&& yes | hp-plugin -p hplip-${HPPLUGIN_VERSION}-plugin.run -i ${HPPRINTER_IP}

# Remove no-longer needed packages and extraneous working directory clutter
RUN \
	apt-get purge --auto-remove -y ca-certificates curl whois \
	&& rm ./* -rf

# Setup script to add printers, and its systemd unit with the correct
# environment variables.
COPY setup.sh .
COPY setup.service /etc/systemd/system/setup.service
RUN \
	chmod +x setup.sh \
	&& sed -i \
		-e "s/@BRPRINTER_IP@/${BRPRINTER_IP}/" \
		-e "s/@HPPRINTER_IP@/${HPPRINTER_IP}/" \
		/etc/systemd/system/setup.service

# Copy configuration files
COPY cupsd.conf /etc/cups
COPY saned.conf /etc/sane.d

# Enable systemd services and start with systemd's init
RUN systemctl enable cups.socket saned.socket setup.service
CMD [ "/sbin/init" ]
