-- SPDX-License-Identifier: MIT
-- Copyright (c) 2022 Chua Hou

local wezterm = require 'wezterm';

-- Allow an override.lua file to provide a function that performs overrides on
-- the returned config table. If it does not exist, use the id function.
local override;
pcall(require, 'override');
if not(pcall(require, 'override')) then
	override = function (x) return x end;
else
	override = require 'override';
end

return override({
	-- Font settings.
	font = wezterm.font_with_fallback({
		{
			family = "Iosevka",
			harfbuzz_features = { "calt=0", "HSKL=1" },
			stretch = "Expanded",
		},
		"Noto Sans Mono CJK JP", -- 日本語用のフォント
	}),
	font_size = 13.5,
	line_height = 1.45,

	-- Disable scroll and tab bars completely.
	enable_scroll_bar = false,
	enable_tab_bar = false,

	-- Disabled since a tiling window manager is used.
	adjust_window_size_when_changing_font_size = false,

	-- Colourscheme either in colours.lua generated by nix, or nonexistent. An
	-- empty colourscheme {} is equal to default settings.
	color_scheme = "hm-colourscheme",

	-- Do not brighten bold colours.
	bold_brightens_ansi_colors = false,

	-- Translucent backgrounds.
	window_background_opacity = 0.92,

	-- Padding.
	window_padding = {
		left = 30,
		right = 30,
		top = 30,
		bottom = 30,
	},

	-- Disable bell sound.
	audible_bell = "Disabled",

	-- Increased scrollback history.
	scrollback_lines = 10000,

	-- Close even on non-clean exit, so that exiting after a non-zero exit code
	-- program will still close the window instantly.
	exit_behavior = "Close",
})
