name: "Build derivations with updated inputs"
on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: cachix/install-nix-action@v20
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: actions/checkout@v3
      - uses: cachix/cachix-action@v12
        with:
          name: chuahou
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: df -h /
      - run: nix flake update
      - run: scripts/ci.sh
      - run: df -h /
