name: "Build GIMP with Python 2 support"
on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'
jobs:
  build-gimp:
    runs-on: ubuntu-latest
    steps:
      - uses: cachix/install-nix-action@v18
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v12
        with:
          name: chuahou
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix build --impure --expr '(import <nixpkgs> { config.permittedInsecurePackages = [ "python-2.7.18.6" "python-2.7.18.6-env" ]; }).gimp.override { withPython = true; }'
