name: "Build GIMP with Python 2 support"
on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'
jobs:
  build-gimp:
    runs-on: ubuntu-latest
    steps:
      - uses: cachix/install-nix-action@v20
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: actions/checkout@v3
      - uses: cachix/cachix-action@v12
        with:
          name: chuahou
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix build --impure --expr '(import <nixpkgs> { overlays = [ (import pkgs/python2-overlay.nix) ]; }).gimp'
